
--- ARQUITECTURA DE MICROSERVICIO DE UNA TIENDA
--- MICROSERVICIO PADRE O GENERAR --- TIENDA --- ORACLE 
--- MICROSERVICIOS HIJOS: PRODUCTOS(ORACLE),
--- EMPLEADOS: H2 ES UNA BASE DE DATOS EN MEMORIA, SIMULACION DE UNA BD

CREATE TABLE TIENDA_30(
ID_TIENDA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
TIPO VARCHAR2(100) NOT NULL 
);

CREATE TABLE PRODUCTOS_30(
ID_PRODUCTO NUMBER PRIMARY KEY, 
NOMBRE VARCHAR2(100) NOT NULL,
PRECIO NUMBER NOT NULL,
ID_TIENDA NUMBER NOT NULL --- LLAVE REFERENCIADA

);






